"""add_performance_indexes

Revision ID: 06b73dd52b46
Revises: 45fd9892c8e0
Create Date: 2026-06-11 03:06:22.306979
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06b73dd52b46'
down_revision: Union[str, None] = '45fd9892c8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_attempt_user_quiz_status', 'lich_su_lam_bai', ['ma_nguoi_dung', 'ma_bai_kiem_tra', 'trang_thai'], unique=False)
    op.create_index('ix_progress_enrollment_completed', 'tien_do_hoc_tap', ['ma_dang_ky_hoc', 'da_hoan_thanh'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_progress_enrollment_completed', table_name='tien_do_hoc_tap')
    op.drop_index('ix_attempt_user_quiz_status', table_name='lich_su_lam_bai')
    # ### end Alembic commands ###
