"""Add password reset fields

Revision ID: 08907a397b36
Revises: 0a06901bf194
Create Date: 2026-06-08 12:03:14.299859
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08907a397b36'
down_revision: Union[str, None] = '0a06901bf194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nguoi_dung', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('nguoi_dung', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_nguoi_dung_reset_token'), 'nguoi_dung', ['reset_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nguoi_dung_reset_token'), table_name='nguoi_dung')
    op.drop_column('nguoi_dung', 'reset_token_expires')
    op.drop_column('nguoi_dung', 'reset_token')
    # ### end Alembic commands ###
