"""Add PayoutRequest table

Revision ID: 0a06901bf194
Revises: 1b3db6051877
Create Date: 2026-06-08 11:00:45.067095
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a06901bf194'
down_revision: Union[str, None] = '1b3db6051877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
