"""remove course prerequisite feature

Revision ID: 1b3db6051877
Revises: e3f21f59d72f
Create Date: 2026-06-07 04:50:06.331108
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b3db6051877'
down_revision: Union[str, None] = 'e3f21f59d72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dieu_kien_tien_quyet_ma_khoa_hoc_chinh', table_name='dieu_kien_tien_quyet')
    op.drop_index('ix_dieu_kien_tien_quyet_ma_khoa_hoc_tien_quyet', table_name='dieu_kien_tien_quyet')
    op.drop_table('dieu_kien_tien_quyet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dieu_kien_tien_quyet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ma_khoa_hoc_chinh', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ma_khoa_hoc_tien_quyet', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ma_khoa_hoc_chinh'], ['khoa_hoc.id'], name='dieu_kien_tien_quyet_ma_khoa_hoc_chinh_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_khoa_hoc_tien_quyet'], ['khoa_hoc.id'], name='dieu_kien_tien_quyet_ma_khoa_hoc_tien_quyet_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='dieu_kien_tien_quyet_pkey'),
    sa.UniqueConstraint('ma_khoa_hoc_chinh', 'ma_khoa_hoc_tien_quyet', name='uq_course_prerequisite')
    )
    op.create_index('ix_dieu_kien_tien_quyet_ma_khoa_hoc_tien_quyet', 'dieu_kien_tien_quyet', ['ma_khoa_hoc_tien_quyet'], unique=False)
    op.create_index('ix_dieu_kien_tien_quyet_ma_khoa_hoc_chinh', 'dieu_kien_tien_quyet', ['ma_khoa_hoc_chinh'], unique=False)
    # ### end Alembic commands ###
