"""add_notification_table

Revision ID: 45fd9892c8e0
Revises: 08907a397b36
Create Date: 2026-06-10 13:49:40.882032
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '45fd9892c8e0'
down_revision: Union[str, None] = '08907a397b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thong_bao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ma_nguoi_dung', sa.Integer(), nullable=False),
    sa.Column('tieu_de', sa.String(length=255), nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.Column('loai', sa.String(length=50), nullable=False),
    sa.Column('da_doc', sa.Boolean(), nullable=False),
    sa.Column('ngay_tao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ma_nguoi_dung'], ['nguoi_dung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thong_bao_ma_nguoi_dung'), 'thong_bao', ['ma_nguoi_dung'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thong_bao_ma_nguoi_dung'), table_name='thong_bao')
    op.drop_table('thong_bao')
    # ### end Alembic commands ###
