"""add thumbnail to course

Revision ID: e3f21f59d72f
Revises: 20260605_0001
Create Date: 2026-06-07 04:25:00.309459
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e3f21f59d72f'
down_revision: Union[str, None] = '20260605_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bai_hoc_da_xuat_ban'), 'bai_hoc', ['da_xuat_ban'], unique=False)
    op.create_index(op.f('ix_bai_hoc_ma_chuong_hoc'), 'bai_hoc', ['ma_chuong_hoc'], unique=False)
    op.create_index(op.f('ix_bai_hoc_thu_tu'), 'bai_hoc', ['thu_tu'], unique=False)
    op.create_index(op.f('ix_bai_hoc_trang_thai_phe_duyet'), 'bai_hoc', ['trang_thai_phe_duyet'], unique=False)
    op.create_index(op.f('ix_bai_hoc_xem_truoc'), 'bai_hoc', ['xem_truoc'], unique=False)
    op.create_index(op.f('ix_chi_tiet_don_hang_ma_don_hang'), 'chi_tiet_don_hang', ['ma_don_hang'], unique=False)
    op.create_index(op.f('ix_chi_tiet_don_hang_ma_khoa_hoc'), 'chi_tiet_don_hang', ['ma_khoa_hoc'], unique=False)
    op.create_index(op.f('ix_chuong_hoc_ma_khoa_hoc'), 'chuong_hoc', ['ma_khoa_hoc'], unique=False)
    op.create_index(op.f('ix_chuong_hoc_thu_tu'), 'chuong_hoc', ['thu_tu'], unique=False)
    op.create_index(op.f('ix_dang_ky_hoc_ma_khoa_hoc'), 'dang_ky_hoc', ['ma_khoa_hoc'], unique=False)
    op.create_index(op.f('ix_dang_ky_hoc_ma_nguoi_dung'), 'dang_ky_hoc', ['ma_nguoi_dung'], unique=False)
    op.create_index(op.f('ix_dang_ky_hoc_ngay_dang_ky'), 'dang_ky_hoc', ['ngay_dang_ky'], unique=False)
    op.create_index(op.f('ix_danh_gia_khoa_hoc_ma_khoa_hoc'), 'danh_gia_khoa_hoc', ['ma_khoa_hoc'], unique=False)
    op.create_index(op.f('ix_danh_gia_khoa_hoc_ma_nguoi_dung'), 'danh_gia_khoa_hoc', ['ma_nguoi_dung'], unique=False)
    op.create_index(op.f('ix_danh_gia_khoa_hoc_ngay_tao'), 'danh_gia_khoa_hoc', ['ngay_tao'], unique=False)
    op.create_index(op.f('ix_danh_gia_khoa_hoc_so_sao'), 'danh_gia_khoa_hoc', ['so_sao'], unique=False)
    op.create_index(op.f('ix_danh_muc_ten_danh_muc'), 'danh_muc', ['ten_danh_muc'], unique=False)
    op.create_index(op.f('ix_danh_sach_yeu_thich_ma_khoa_hoc'), 'danh_sach_yeu_thich', ['ma_khoa_hoc'], unique=False)
    op.create_index(op.f('ix_danh_sach_yeu_thich_ma_nguoi_dung'), 'danh_sach_yeu_thich', ['ma_nguoi_dung'], unique=False)
    op.create_index(op.f('ix_danh_sach_yeu_thich_ngay_them'), 'danh_sach_yeu_thich', ['ngay_them'], unique=False)
    op.create_index(op.f('ix_dieu_kien_tien_quyet_ma_khoa_hoc_chinh'), 'dieu_kien_tien_quyet', ['ma_khoa_hoc_chinh'], unique=False)
    op.create_index(op.f('ix_dieu_kien_tien_quyet_ma_khoa_hoc_tien_quyet'), 'dieu_kien_tien_quyet', ['ma_khoa_hoc_tien_quyet'], unique=False)
    op.create_index(op.f('ix_don_hang_ma_giam_gia_id'), 'don_hang', ['ma_giam_gia_id'], unique=False)
    op.create_index(op.f('ix_don_hang_ma_giao_dich'), 'don_hang', ['ma_giao_dich'], unique=False)
    op.create_index(op.f('ix_don_hang_ma_nguoi_dung'), 'don_hang', ['ma_nguoi_dung'], unique=False)
    op.create_index(op.f('ix_don_hang_ngay_tao'), 'don_hang', ['ngay_tao'], unique=False)
    op.create_index(op.f('ix_don_hang_ngay_thanh_toan'), 'don_hang', ['ngay_thanh_toan'], unique=False)
    op.create_index(op.f('ix_don_hang_phuong_thuc_thanh_toan'), 'don_hang', ['phuong_thuc_thanh_toan'], unique=False)
    op.create_index(op.f('ix_don_hang_trang_thai'), 'don_hang', ['trang_thai'], unique=False)
    op.add_column('khoa_hoc', sa.Column('anh_dai_dien', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_khoa_hoc_da_xuat_ban'), 'khoa_hoc', ['da_xuat_ban'], unique=False)
    op.create_index(op.f('ix_khoa_hoc_danh_gia_trung_binh'), 'khoa_hoc', ['danh_gia_trung_binh'], unique=False)
    op.create_index(op.f('ix_khoa_hoc_gia_tien'), 'khoa_hoc', ['gia_tien'], unique=False)
    op.create_index(op.f('ix_khoa_hoc_ma_danh_muc'), 'khoa_hoc', ['ma_danh_muc'], unique=False)
    op.create_index(op.f('ix_khoa_hoc_ma_giang_vien'), 'khoa_hoc', ['ma_giang_vien'], unique=False)
    op.create_index(op.f('ix_khoa_hoc_ngay_tao'), 'khoa_hoc', ['ngay_tao'], unique=False)
    op.create_index(op.f('ix_khoa_hoc_tieu_de'), 'khoa_hoc', ['tieu_de'], unique=False)
    op.create_index(op.f('ix_khoa_hoc_trang_thai_phe_duyet'), 'khoa_hoc', ['trang_thai_phe_duyet'], unique=False)
    op.create_index(op.f('ix_khoa_hoc_trinh_do'), 'khoa_hoc', ['trinh_do'], unique=False)
    op.drop_constraint('ma_giam_gia_ma_code_key', 'ma_giam_gia', type_='unique')
    op.create_index(op.f('ix_ma_giam_gia_ma_code'), 'ma_giam_gia', ['ma_code'], unique=True)
    op.create_index(op.f('ix_ma_giam_gia_ngay_het_han'), 'ma_giam_gia', ['ngay_het_han'], unique=False)
    op.alter_column('nguoi_dung', 'mat_khau',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_nguoi_dung_ngay_tao'), 'nguoi_dung', ['ngay_tao'], unique=False)
    op.create_index(op.f('ix_nguoi_dung_trang_thai_hoat_dong'), 'nguoi_dung', ['trang_thai_hoat_dong'], unique=False)
    op.create_index(op.f('ix_nguoi_dung_vai_tro'), 'nguoi_dung', ['vai_tro'], unique=False)
    op.create_index(op.f('ix_noi_dung_bai_hoc_loai_noi_dung'), 'noi_dung_bai_hoc', ['loai_noi_dung'], unique=False)
    op.create_index(op.f('ix_noi_dung_bai_hoc_ma_bai_hoc'), 'noi_dung_bai_hoc', ['ma_bai_hoc'], unique=False)
    op.create_index(op.f('ix_noi_dung_bai_hoc_thu_tu'), 'noi_dung_bai_hoc', ['thu_tu'], unique=False)
    op.create_index(op.f('ix_tien_do_hoc_tap_da_hoan_thanh'), 'tien_do_hoc_tap', ['da_hoan_thanh'], unique=False)
    op.create_index(op.f('ix_tien_do_hoc_tap_ma_bai_hoc'), 'tien_do_hoc_tap', ['ma_bai_hoc'], unique=False)
    op.create_index(op.f('ix_tien_do_hoc_tap_ma_dang_ky_hoc'), 'tien_do_hoc_tap', ['ma_dang_ky_hoc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tien_do_hoc_tap_ma_dang_ky_hoc'), table_name='tien_do_hoc_tap')
    op.drop_index(op.f('ix_tien_do_hoc_tap_ma_bai_hoc'), table_name='tien_do_hoc_tap')
    op.drop_index(op.f('ix_tien_do_hoc_tap_da_hoan_thanh'), table_name='tien_do_hoc_tap')
    op.drop_index(op.f('ix_noi_dung_bai_hoc_thu_tu'), table_name='noi_dung_bai_hoc')
    op.drop_index(op.f('ix_noi_dung_bai_hoc_ma_bai_hoc'), table_name='noi_dung_bai_hoc')
    op.drop_index(op.f('ix_noi_dung_bai_hoc_loai_noi_dung'), table_name='noi_dung_bai_hoc')
    op.drop_index(op.f('ix_nguoi_dung_vai_tro'), table_name='nguoi_dung')
    op.drop_index(op.f('ix_nguoi_dung_trang_thai_hoat_dong'), table_name='nguoi_dung')
    op.drop_index(op.f('ix_nguoi_dung_ngay_tao'), table_name='nguoi_dung')
    op.alter_column('nguoi_dung', 'mat_khau',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_ma_giam_gia_ngay_het_han'), table_name='ma_giam_gia')
    op.drop_index(op.f('ix_ma_giam_gia_ma_code'), table_name='ma_giam_gia')
    op.create_unique_constraint('ma_giam_gia_ma_code_key', 'ma_giam_gia', ['ma_code'])
    op.drop_index(op.f('ix_khoa_hoc_trinh_do'), table_name='khoa_hoc')
    op.drop_index(op.f('ix_khoa_hoc_trang_thai_phe_duyet'), table_name='khoa_hoc')
    op.drop_index(op.f('ix_khoa_hoc_tieu_de'), table_name='khoa_hoc')
    op.drop_index(op.f('ix_khoa_hoc_ngay_tao'), table_name='khoa_hoc')
    op.drop_index(op.f('ix_khoa_hoc_ma_giang_vien'), table_name='khoa_hoc')
    op.drop_index(op.f('ix_khoa_hoc_ma_danh_muc'), table_name='khoa_hoc')
    op.drop_index(op.f('ix_khoa_hoc_gia_tien'), table_name='khoa_hoc')
    op.drop_index(op.f('ix_khoa_hoc_danh_gia_trung_binh'), table_name='khoa_hoc')
    op.drop_index(op.f('ix_khoa_hoc_da_xuat_ban'), table_name='khoa_hoc')
    op.drop_column('khoa_hoc', 'anh_dai_dien')
    op.drop_index(op.f('ix_don_hang_trang_thai'), table_name='don_hang')
    op.drop_index(op.f('ix_don_hang_phuong_thuc_thanh_toan'), table_name='don_hang')
    op.drop_index(op.f('ix_don_hang_ngay_thanh_toan'), table_name='don_hang')
    op.drop_index(op.f('ix_don_hang_ngay_tao'), table_name='don_hang')
    op.drop_index(op.f('ix_don_hang_ma_nguoi_dung'), table_name='don_hang')
    op.drop_index(op.f('ix_don_hang_ma_giao_dich'), table_name='don_hang')
    op.drop_index(op.f('ix_don_hang_ma_giam_gia_id'), table_name='don_hang')
    op.drop_index(op.f('ix_dieu_kien_tien_quyet_ma_khoa_hoc_tien_quyet'), table_name='dieu_kien_tien_quyet')
    op.drop_index(op.f('ix_dieu_kien_tien_quyet_ma_khoa_hoc_chinh'), table_name='dieu_kien_tien_quyet')
    op.drop_index(op.f('ix_danh_sach_yeu_thich_ngay_them'), table_name='danh_sach_yeu_thich')
    op.drop_index(op.f('ix_danh_sach_yeu_thich_ma_nguoi_dung'), table_name='danh_sach_yeu_thich')
    op.drop_index(op.f('ix_danh_sach_yeu_thich_ma_khoa_hoc'), table_name='danh_sach_yeu_thich')
    op.drop_index(op.f('ix_danh_muc_ten_danh_muc'), table_name='danh_muc')
    op.drop_index(op.f('ix_danh_gia_khoa_hoc_so_sao'), table_name='danh_gia_khoa_hoc')
    op.drop_index(op.f('ix_danh_gia_khoa_hoc_ngay_tao'), table_name='danh_gia_khoa_hoc')
    op.drop_index(op.f('ix_danh_gia_khoa_hoc_ma_nguoi_dung'), table_name='danh_gia_khoa_hoc')
    op.drop_index(op.f('ix_danh_gia_khoa_hoc_ma_khoa_hoc'), table_name='danh_gia_khoa_hoc')
    op.drop_index(op.f('ix_dang_ky_hoc_ngay_dang_ky'), table_name='dang_ky_hoc')
    op.drop_index(op.f('ix_dang_ky_hoc_ma_nguoi_dung'), table_name='dang_ky_hoc')
    op.drop_index(op.f('ix_dang_ky_hoc_ma_khoa_hoc'), table_name='dang_ky_hoc')
    op.drop_index(op.f('ix_chuong_hoc_thu_tu'), table_name='chuong_hoc')
    op.drop_index(op.f('ix_chuong_hoc_ma_khoa_hoc'), table_name='chuong_hoc')
    op.drop_index(op.f('ix_chi_tiet_don_hang_ma_khoa_hoc'), table_name='chi_tiet_don_hang')
    op.drop_index(op.f('ix_chi_tiet_don_hang_ma_don_hang'), table_name='chi_tiet_don_hang')
    op.drop_index(op.f('ix_bai_hoc_xem_truoc'), table_name='bai_hoc')
    op.drop_index(op.f('ix_bai_hoc_trang_thai_phe_duyet'), table_name='bai_hoc')
    op.drop_index(op.f('ix_bai_hoc_thu_tu'), table_name='bai_hoc')
    op.drop_index(op.f('ix_bai_hoc_ma_chuong_hoc'), table_name='bai_hoc')
    op.drop_index(op.f('ix_bai_hoc_da_xuat_ban'), table_name='bai_hoc')
    # ### end Alembic commands ###
