"""drop_wishlist_table

Revision ID: f63df47a2ace
Revises: 06b73dd52b46
Create Date: 2026-06-15 06:25:40.893967
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f63df47a2ace'
down_revision: Union[str, None] = '06b73dd52b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_danh_sach_yeu_thich_ma_khoa_hoc', table_name='danh_sach_yeu_thich')
    op.drop_index('ix_danh_sach_yeu_thich_ma_nguoi_dung', table_name='danh_sach_yeu_thich')
    op.drop_index('ix_danh_sach_yeu_thich_ngay_them', table_name='danh_sach_yeu_thich')
    op.drop_table('danh_sach_yeu_thich')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danh_sach_yeu_thich',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ma_nguoi_dung', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ma_khoa_hoc', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ngay_them', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ma_khoa_hoc'], ['khoa_hoc.id'], name='danh_sach_yeu_thich_ma_khoa_hoc_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_nguoi_dung'], ['nguoi_dung.id'], name='danh_sach_yeu_thich_ma_nguoi_dung_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='danh_sach_yeu_thich_pkey'),
    sa.UniqueConstraint('ma_nguoi_dung', 'ma_khoa_hoc', name='uq_wishlist_user_course')
    )
    op.create_index('ix_danh_sach_yeu_thich_ngay_them', 'danh_sach_yeu_thich', ['ngay_them'], unique=False)
    op.create_index('ix_danh_sach_yeu_thich_ma_nguoi_dung', 'danh_sach_yeu_thich', ['ma_nguoi_dung'], unique=False)
    op.create_index('ix_danh_sach_yeu_thich_ma_khoa_hoc', 'danh_sach_yeu_thich', ['ma_khoa_hoc'], unique=False)
    # ### end Alembic commands ###
